# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-26 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_userhistorymodel_userprofilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='file_url',
            field=models.CharField(default='init', max_length=256),
        ),
    ]
