# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-12-26 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_musicmodel_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicmodel',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
